apiVersion: v1
kind: Service
metadata:
  name: sdoc
  labels:
    name: sdoc
spec:
  ports:
    - nodePort: 30163 
      port: 8080      
      targetPort: 8080  
      protocol: TCP
  selector:           
    app: sdoc
  type: NodePort       

